-   id: kubeval
    name: kubeval
    description: Run kubeval, a linter for k8s manifest files
    entry: hooks/kubeval.bash
    language: script
-   id: dynamic-pylint
    name: dynamic pylint
    description: Run pylint lint, a linter for python
    entry: hooks/dynamic_pylint.py
    language: script
    types: [python]
-   id: openapi
    name: OpenAPI Linter
    description: This hook will lint your OpenAPI specifications.
    entry: hooks/run_speccy.sh
    language: script
    files: (schema|swagger).(yaml|yml)$
