- id: kubeval
  name: kubeval
  description: Run kubeval, a linter for k8s manifest files
  entry: hooks/kubeval.bash
  language: script
- id: helmlint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: hooks/helmlint.bash
  language: script
  files: \.((ya?ml)|(tpl))$
